name: Telegram Bot Auto Poster

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        PEXELS_KEY: ${{ secrets.Pexels_KEY }}
      run: python main.py
